### ISSUE TITLE
prettify-symbol-mode and context-coloring-mode 

### ISSUE THREAD

**Issue by aurelienbottazini** [jacksonrayhamilton/context-coloring#3]
It seems the two don't play well together.

When i enable context-coloring, the symbols are not _prettified_ anymore.

![rlc36mgckl](https://cloud.githubusercontent.com/assets/32635/20711886/1d57e7c2-b642-11e6-9d15-6438640ad237.gif)

This is the code used to prettify symbols:
https://gist.github.com/DeLaGuardo/fe1f3d9397d6ef7468460d54d5601156

emacs-version: 
GNU Emacs 25.1.1 (x86_64-apple-darwin16.0.0, NS appkit-1504.00 Version 10.12 (Build 16A323)) of 2016-10-17

Context coloring mode version
8.0.1

**Comment by aurelienbottazini** [comment]
same behaviour with `emacs-lisp-mode`

**Comment by jacksonrayhamilton** [comment]
I think this problem arises due to Context Coloring turning off Font Lock, and Prettify Symbols relies on Font Lock.

Evaluating the following Lisp in a Context Coloring and Prettify Symbols buffer results in the symbols being prettified once:

```lisp
(with-silent-modifications
  (save-excursion
    (font-lock-fontify-keywords-region (point-min) (point-max))))
```

I suppose we could tack that onto the end of `context-coloring-colorize`, but it would only be useful for the subset of users who use other modes that rely on Font Lock, and might slow things down for everyone else. A solution would be to add a "context-coloring-after-colorize-hook," to allow users to integrate Context Coloring with their own configurations.

I'm hesitant to implement / execute workarounds for particular other modes relying on Font Lock, since the list of modes is unbounded. However, since this could be considered a general fix for modes relying on Font Lock keywords, it's easier to justify.

Would you like to take [this branch](https://github.com/jacksonrayhamilton/context-coloring/pull/5) for a spin and see if my fix works for you?

**Comment by aurelienbottazini** [comment]
Hello @jacksonrayhamilton 

It works with your fix!

![image](https://cloud.githubusercontent.com/assets/32635/20752720/0d9ca950-b703-11e6-9dd5-211288d86aa7.png)

;)

**Comment by aurelienbottazini** [comment]
Unfortunately I am not competent enough with `lisp` to give a good opinion on your suggestions.

But I do agree performance is really important. One thing I like with emacs is how well it handles large files (compared to other editors).

Having workarounds only  for modes part of standard emacs seems reasonable to me.
